13.03.2020 20:02:55 Checking for system tray...
13.03.2020 20:02:55 Starting pgAdmin4 server...
13.03.2020 20:02:55 Creating server object, port:57134, key:bb39db5c-2965-4a1c-b669-11d4fbd33009, logfile:C:/Users/PAUL/.pgAdmin4.2123502176.log
13.03.2020 20:02:55 Python Path: C:/Program Files/PostgreSQL/10/pgAdmin 4/venv/Lib/site-packages;C:/Program Files/PostgreSQL/10/pgAdmin 4/venv/DLLs;C:/Program Files/PostgreSQL/10/pgAdmin 4/venv/Lib
13.03.2020 20:02:55 Python Home: C:/Program Files/PostgreSQL/10/pgAdmin 4/venv
13.03.2020 20:02:55 Initializing Python...
13.03.2020 20:02:55 Python initialized.
13.03.2020 20:02:55 Adding new additional path elements
13.03.2020 20:02:55 Redirecting stderr...
13.03.2020 20:02:55 stderr redirected successfully.
13.03.2020 20:02:55 Initializing server...
13.03.2020 20:02:55 Webapp Path: C:/Program Files/PostgreSQL/10/pgAdmin 4/web/pgAdmin4.py
13.03.2020 20:02:55 Server initialized.
13.03.2020 20:02:55 Starting Server Thread...
13.03.2020 20:02:55 Open the application code and run it.
13.03.2020 20:02:55 Set the port number, key and force SERVER_MODE off
13.03.2020 20:02:55 PyRun_SimpleFile launching application server...
13.03.2020 20:02:56 Application Server URL: http://127.0.0.1:57134/?key=bb39db5c-2965-4a1c-b669-11d4fbd33009
13.03.2020 20:02:56 The server should be up, we'll attempt to connect and get a response. Ping the server
13.03.2020 20:04:10 Attempt to connect one more time in case of a long network timeout while looping
13.03.2020 20:04:10 Everything works fine, successfully started pgAdmin4.
